### ISSUE TITLE
Deploy configs

### ISSUE THREAD

**Issue by matiasvlevi** [DO2-Momo/do2iso#2]
# Deploy configs & assets

Place configurations in `/usr/share`, and place user specific configutations in `/root/` 

# Wallpaper

Add the wallpapers from `DO2-Momo/assets` and display one of them with `feh` in the i3 environement, the background has to be there at boot

# Add the i3 config
This configuration [DO2-Momo/yarpiso#4](https://github.com/DO2-Momo/yarpiso/issues/4) has to be present in the `/root/` of this ISO, keep in mind you find your i3 config in `~/.config/i3/config`, this should be `/root/.config/i3/config` in the ISO files

**Comment by Mhikmat** [comment]
I added the minimal i3 configs
